#!/usr/bin/env bash



alias e="$EDITOR"
alias v="$EDITOR -R"

# exa
alias l='exa'
alias ll='exa -haal'

# for safety
alias rm='rm -I'

# misc
alias df='df -h'
alias du='du -h'

# git
g () {
  [[ $# -eq 0 ]] && { git status -s; return; }
  git "$@"
}
# git completion
if [[ -f /usr/share/bash-completion/completions/git ]]; then
  . /usr/share/bash-completion/completions/git
  __git_complete g __git_main
fi

# auto-open
alias xo='xdg-open'

# docker-related
alias doco='docker-compose'

# timestamp
tsnow () {
  date +%Y-%m-%d_%H-%M
}
