#!/usr/bin/env bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# History
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# Ignore EOF
export IGNOREEOF=2

# Update the values of LINES and COLUMNS on resize
shopt -s checkwinsize

# Allow ** glob
shopt -s globstar

export PATH="$HOME/.local/bin:$PATH"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  if [[ -r ~/.dircolors ]]; then
    eval "$(dircolors -b ~/.dircolors)"
  else
    eval "$(dircolors -b)"
  fi
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# Editor
export EDITOR='nvim'

# Bash aliases
[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases

# Bash completion
[[ -f /etc/bash_completion ]] && ! shopt -oq posix && . /etc/bash_completion

# keychain
eval $(keychain --eval --agents ssh --quiet)

# fzf
if [[ -d "$HOME/.fzf" ]]; then
  export PATH="$HOME/.fzf/bin:$PATH"

  [[ $- == *i* ]] && source "$HOME/.fzf/shell/completion.bash" 2> /dev/null
  source "/home/alex/.fzf/shell/key-bindings.bash"

  complete -F _fzf_path_completion -o default -o bashdefault e
  complete -F _fzf_path_completion -o default -o bashdefault v
  export FZF_DEFAULT_COMMAND='fd --type f --hidden -E .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# Colored man pages
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# Git prompt
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUPSTREAM="auto"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv init --path)"
fi

# Poetry
export PATH="$HOME/.poetry/bin:$PATH"

# Virtualenv
export VIRTUAL_ENV_DISABLE_PROMPT=1 # disable default prompt
# export WORKON_HOME=$HOME/.virtualenvs
# [[ -f /usr/local/bin/virtualenvwrapper.sh ]] && . /usr/local/bin/virtualenvwrapper.sh

# venv prompt
__venv_ps1 () {
  [[ -n $VIRTUAL_ENV ]] && echo "($(basename "$VIRTUAL_ENV")) "
}

# conda prompt
__conda_ps1 () {
  [[ -n $CONDA_DEFAULT_ENV ]] && echo "[$CONDA_DEFAULT_ENV] "
}

# Anaconda
CONDA_BIN="$HOME/anaconda3/bin/conda"
if [[ -x $CONDA_BIN ]]; then
  conda () {
    echo "initializing conda..." >&2
    eval "$($CONDA_BIN shell.bash hook)"
    # the "real" conda defined by the above init hook
    conda "$@"
  }
fi

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
if [[ -f $VOLTA_HOME/load.sh ]]; then
  source "$VOLTA_HOME/load.sh"
fi

# Bash PS1 prompt
PS1='\n\[\e[1;36m\]\u\[\e[0m\] \h \[\e[1m\]\[\e[1;34m\]\w\[\e[0m\]\[\e[0m\]$(__git_ps1 " (%s)")\n$(__venv_ps1)$(__conda_ps1)\[\e[0;1m\]\$ \[\e[0m\]'
