set nocompatible
set encoding=utf-8
scriptencoding utf-8

" Backup/swap files
set backupcopy=yes
set backupdir=~/.vim/backup
set directory=~/.vim/backup



""" Global mapping options

" Easier :
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

" Leader keys
let mapleader = "\<Space>"
let maplocalleader = "\\"

" No delay when pressing Esc
set timeoutlen=1000 ttimeoutlen=0



""" Display

set laststatus=2
set showcmd
set noshowmode

" Colors
if has("termguicolors")
  set termguicolors
endif
let base16colorspace=256
set background={{ vim.background }}

" Show invisibles
set list
set listchars=tab:»\ ,trail:·
let &showbreak = '↳ '

" Conceal
let g:tex_conceal = 'admg'

" Line highlighting/numbering
set number
set relativenumber
set cursorline
set colorcolumn=100

" Matching brackets
set showmatch

" No bells
set noerrorbells visualbell t_vb=
autocmd GuiEnter * set visualbell t_vb=



""" Navigation

" Correct backspace/movement wrapping
set backspace=indent,eol,start
set whichwrap+=<,>,h,l,[,]
nnoremap <expr> j v:count ? 'j' : 'gj'
nnoremap <expr> k v:count ? 'k' : 'gk'

" Better wrapping behavior
set breakindent
set display=lastline

" Scrolloff
set scrolloff=5
set sidescrolloff=5

" Folding
nnoremap , za
vnoremap , zf
set foldlevelstart=99

" Netrw navigation
nnoremap <F1> :Vex<CR>
let g:netrw_liststyle=3

" Buffer navigation
nnoremap <BS> <C-^>
set hidden
let g:netrw_altfile = 1

" Split nagivation
nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
set splitright
set splitbelow



""" Editing

" Indentation
set autoindent
set smartindent
set tabstop=4
set softtabstop=2
set shiftwidth=2
set expandtab

nnoremap <Left> <<
nnoremap <Right> >>
vnoremap <Left> <gv
vnoremap <Right> >gv

" Filetype extras
filetype plugin indent on

" Commenting
autocmd FileType c,cpp,h,hpp setlocal commentstring=//\ %s
autocmd FileType ocaml setlocal commentstring=(*\ %s\ *)



""" Command-line behavior

" Search
set incsearch
set hlsearch
set ignorecase smartcase
let @/ = ""
nnoremap <leader>n :noh<CR>

" Completion options
set path=.,**
set wildmode=list,full
set wildmenu

" Build systems
nnoremap <F10> :lwindow<CR>
" No qf in :ls/:bn/etc, and use abs line numbers (from romainl's vim-qf)
autocmd FileType qf set nobuflisted | setlocal norelativenumber number



""" Plugins

let g:python_host_prog =  $HOME . '/.pyenv/versions/neovim-python2/bin/python'
let g:python3_host_prog = $HOME . '/.pyenv/versions/neovim-python3/bin/python'

call plug#begin('~/.vim/plugged')

Plug 'chriskempson/base16-vim'
Plug 'lewis6991/gitsigns.nvim'
Plug 'luukvbaal/statuscol.nvim'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
let $FZF_DEFAULT_COMMAND = 'fd --type f --hidden -E .git'
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>f :Files<CR>
nnoremap <leader>F :Files <C-R>=expand('%:h')<CR><CR>

Plug 'morhetz/gruvbox'
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_invert_selection = 0
let g:gruvbox_italic = 1
let g:gruvbox_italicize_strings = 0
let g:gruvbox_sign_column = 'bg0'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme = '{{ vim.airline_theme }}'
let g:airline_solarized_bg = '{{ vim.background }}'
let g:airline_powerline_fonts = 0
let g:airline_symbols_ascii = 1
let g:airline_extensions = ['tabline']
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#show_tab_type = 0
let g:airline#extensions#tabline#tab_min_count = 2
let g:airline#extensions#tabline#tab_nr_type = 1
nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9

Plug 'tpope/vim-fugitive'
nnoremap <leader>gs :Git status<CR>

Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
let g:pandoc#modules#enabled =
      \ ['command', 'folding', 'formatting', 'hypertext', 'toc']
let g:pandoc#modules#disabled = ['chdir']
let g:pandoc#command#autoexec_on_writes = 1
let g:pandoc#folding#fdc = 0
let g:pandoc#syntax#use_definition_lists = 0

Plug 'echasnovski/mini.nvim', { 'branch': 'stable' }

Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }

Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'
Plug 'neovim/nvim-lspconfig'

call plug#end()



" Set colorscheme after plugin section for plugin-added colorschemes
color {{ vim.color }}



""" Misc Lua setup

lua << EOF
vim.cmd('highlight link GitSignsAdd GruvboxGreenSign')
vim.cmd('highlight link GitSignsChange GruvboxBlueSign')
vim.cmd('highlight link GitSignsDelete GruvboxRedSign')
require('gitsigns').setup({
  on_attach = function(bufnr)
    local gitsigns = require('gitsigns')
    local opts = { buffer = bufnr }
    local km = vim.keymap.set

    km('n', ']c', function()
      if vim.wo.diff then
        vim.cmd.normal({ ']c', bang = true })
      else
        gitsigns.nav_hunk('next')
      end
    end)
    km('n', '[c', function()
      if vim.wo.diff then
        vim.cmd.normal({ '[c', bang = true })
      else
        gitsigns.nav_hunk('prev')
      end
    end)

    km('n', '<leader>hs', gitsigns.stage_hunk)
    km('n', '<leader>hr', gitsigns.reset_hunk)
    km('v', '<leader>hs', function()
      gitsigns.stage_hunk { vim.fn.line('.'), vim.fn.line('v') }
    end)
    km('v', '<leader>hr', function()
      gitsigns.reset_hunk { vim.fn.line('.'), vim.fn.line('v') }
    end)
    km('n', '<leader>hu', gitsigns.undo_stage_hunk)
  end
})

require('mini.ai').setup({})

vim.cmd('highlight link MiniIndentscopeSymbol LineNr')
require('mini.indentscope').setup({
  draw = {
    animation = require('mini.indentscope').gen_animation.none(),
  },
  options = {
    border = 'top',
    indent_at_cursor = false,
  },
})

require('mini.pairs').setup({})

local statuscol_builtin = require('statuscol.builtin')
require('statuscol').setup({
  relculright = true,
  segments = {
    { text = { statuscol_builtin.foldfunc } },
    {
      sign = {
        namespace = { "diagnostic/signs" },
        maxwidth = 2,
        auto = true,
      },
    },
    { text = { statuscol_builtin.lnumfunc } },
    {
      sign = {
        namespace = { ".*" },
        maxwidth = 1,
        colwidth = 1,
        wrap = true,
      },
    },
  },
})
EOF


""" Treesitter setup

lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "lua", "vim", "vimdoc", "query",
    "bash", "make",
    "c", "cpp",
    "python",
    "rust",
    "css", "html", "javascript", "typescript",
    "json", "json5", "jsonc",
    "toml", "yaml",
  },
  auto_install = false,
  highlight = {
    enable = true,
  }
}
EOF



""" LSP setup

lua << EOF
require("mason").setup()
require("mason-lspconfig").setup()

-- Global mappings
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist)

vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    vim.bo[ev.buf].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Buffer-local mappings
    local opts = { buffer = ev.buf }
    local km = vim.keymap.set

    km('n', 'gD', vim.lsp.buf.declaration, opts)
    km('n', 'gd', vim.lsp.buf.definition, opts)
    km('n', '<leader>li', vim.lsp.buf.implementation, opts)
    km('n', '<leader>ls', vim.lsp.buf.signature_help, opts)
    km('n', '<leader>lt', vim.lsp.buf.type_definition, opts)
    km('n', '<leader>lr', vim.lsp.buf.rename, opts)
    km('n', 'gr', vim.lsp.buf.references, opts)
    km({ 'n', 'v' }, '<leader>la', vim.lsp.buf.code_action, opts)
    km('n', '<leader>lf', function()
      vim.lsp.buf.format { async = true }
    end, opts)

    km('n', '<leader>wa', vim.lsp.buf.add_workspace_folder)
    km('n', '<leader>wr', vim.lsp.buf.remove_workspace_folder)
    km('n', '<leader>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
  end,
})

local lspconfig = require'lspconfig'
local servers = {
  -- Python
  'pyright',
  'ruff',

  -- Rust
  'rust_analyzer',

  -- Typescript/Javascript
  'ts_ls',
}
for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    }
  }
end

EOF
